# Generated by Django 6.0.7 on 2026-08-05 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('movie', 'user')},
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.movie'),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review',
        ),
    ]
