# Generated by Django 6.0.7 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_author_reviews_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
